[application]

name = "baker"

[web.app]

# HTML title tag content
title = "Baker"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "xyz.wanye7300"
publisher = "Wanye_7300"
icon = ["icons/icon.ico", "icons/icon.png"]
resources = ["assets/"]
copyright = "Copyright (c) 2026 Wanye_7300"
category = "Utility"
